utils::globalVariables(c(".data", "non_markers", ".",
                         "batch",
                         "id",
                         "desc",
                         "n",
                         "label",
                         "marker",
                         "sd",
                         "mean",
                         "V1",
                         "V2",
                         "sample_id",
                         "Reduction",
                         "Corrected",
                         "Uncorrected",
                         "value",
                         "marker_class",
                         "antigen"))
